apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-registry-proxy-config
  namespace: docker-registry
data:
  registry.conf: |-
    server {
      listen 8080;
      server_name docker-ecr.internal.vnatarov.io;

      # disable any limits to avoid HTTP 413 for large image uploads
      client_max_body_size 0;
      # required to avoid HTTP 411
      chunked_transfer_encoding on;
    
      # http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      client_max_body_size 0;
      chunked_transfer_encoding on;
    
      location / {
       proxy_pass                          "{{ .Env.DOCKER_REGISTRY_SERVER }}";
       proxy_set_header  Host              "{{ .Env.DOCKER_REGISTRY_SERVER | strings.ReplaceAll "https://" "" }}";
       proxy_set_header  Authorization     "Basic {{ base64.Encode .Env.REGISTRY_BASICAUTH }}";       
       proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
       proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto "https";
       proxy_read_timeout                  900;
      }

      location /tmp {
        proxy_pass                          https://XXXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com;
        proxy_set_header  Host              "XXXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com";
        proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto "https";
        proxy_read_timeout                  900;
      }
    }